// Code generated by protoc-gen-go. DO NOT EDIT.
// source: framework.proto

package pbgo

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 连接成功后服务器节点回复验证信息
type ServiceIdentifyACK struct {
	ServiceName          string   `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ServiceId            string   `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	ServerStartTime      uint64   `protobuf:"varint,3,opt,name=server_start_time,json=serverStartTime,proto3" json:"server_start_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceIdentifyACK) Reset()         { *m = ServiceIdentifyACK{} }
func (m *ServiceIdentifyACK) String() string { return proto.CompactTextString(m) }
func (*ServiceIdentifyACK) ProtoMessage()    {}
func (*ServiceIdentifyACK) Descriptor() ([]byte, []int) {
	return fileDescriptor_d31604874e01146d, []int{0}
}

func (m *ServiceIdentifyACK) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceIdentifyACK.Unmarshal(m, b)
}
func (m *ServiceIdentifyACK) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceIdentifyACK.Marshal(b, m, deterministic)
}
func (m *ServiceIdentifyACK) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceIdentifyACK.Merge(m, src)
}
func (m *ServiceIdentifyACK) XXX_Size() int {
	return xxx_messageInfo_ServiceIdentifyACK.Size(m)
}
func (m *ServiceIdentifyACK) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceIdentifyACK.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceIdentifyACK proto.InternalMessageInfo

func (m *ServiceIdentifyACK) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *ServiceIdentifyACK) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

func (m *ServiceIdentifyACK) GetServerStartTime() uint64 {
	if m != nil {
		return m.ServerStartTime
	}
	return 0
}

// PingReq 心跳包
type PingReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingReq) Reset()         { *m = PingReq{} }
func (m *PingReq) String() string { return proto.CompactTextString(m) }
func (*PingReq) ProtoMessage()    {}
func (*PingReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d31604874e01146d, []int{1}
}

func (m *PingReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingReq.Unmarshal(m, b)
}
func (m *PingReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingReq.Marshal(b, m, deterministic)
}
func (m *PingReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingReq.Merge(m, src)
}
func (m *PingReq) XXX_Size() int {
	return xxx_messageInfo_PingReq.Size(m)
}
func (m *PingReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PingReq.DiscardUnknown(m)
}

var xxx_messageInfo_PingReq proto.InternalMessageInfo

// PingAck 心跳包回复
type PingAck struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingAck) Reset()         { *m = PingAck{} }
func (m *PingAck) String() string { return proto.CompactTextString(m) }
func (*PingAck) ProtoMessage()    {}
func (*PingAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_d31604874e01146d, []int{2}
}

func (m *PingAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingAck.Unmarshal(m, b)
}
func (m *PingAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingAck.Marshal(b, m, deterministic)
}
func (m *PingAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingAck.Merge(m, src)
}
func (m *PingAck) XXX_Size() int {
	return xxx_messageInfo_PingAck.Size(m)
}
func (m *PingAck) XXX_DiscardUnknown() {
	xxx_messageInfo_PingAck.DiscardUnknown(m)
}

var xxx_messageInfo_PingAck proto.InternalMessageInfo

// CSPingReq 客户端连接后 发送ping消息
type CSPingReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CSPingReq) Reset()         { *m = CSPingReq{} }
func (m *CSPingReq) String() string { return proto.CompactTextString(m) }
func (*CSPingReq) ProtoMessage()    {}
func (*CSPingReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d31604874e01146d, []int{3}
}

func (m *CSPingReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CSPingReq.Unmarshal(m, b)
}
func (m *CSPingReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CSPingReq.Marshal(b, m, deterministic)
}
func (m *CSPingReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CSPingReq.Merge(m, src)
}
func (m *CSPingReq) XXX_Size() int {
	return xxx_messageInfo_CSPingReq.Size(m)
}
func (m *CSPingReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CSPingReq.DiscardUnknown(m)
}

var xxx_messageInfo_CSPingReq proto.InternalMessageInfo

// SCPingAck 服务端收到客户端的ping消息后返回
type SCPingAck struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SCPingAck) Reset()         { *m = SCPingAck{} }
func (m *SCPingAck) String() string { return proto.CompactTextString(m) }
func (*SCPingAck) ProtoMessage()    {}
func (*SCPingAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_d31604874e01146d, []int{4}
}

func (m *SCPingAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SCPingAck.Unmarshal(m, b)
}
func (m *SCPingAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SCPingAck.Marshal(b, m, deterministic)
}
func (m *SCPingAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SCPingAck.Merge(m, src)
}
func (m *SCPingAck) XXX_Size() int {
	return xxx_messageInfo_SCPingAck.Size(m)
}
func (m *SCPingAck) XXX_DiscardUnknown() {
	xxx_messageInfo_SCPingAck.DiscardUnknown(m)
}

var xxx_messageInfo_SCPingAck proto.InternalMessageInfo

type CSSendMsgReq struct {
	Msg                  []byte   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CSSendMsgReq) Reset()         { *m = CSSendMsgReq{} }
func (m *CSSendMsgReq) String() string { return proto.CompactTextString(m) }
func (*CSSendMsgReq) ProtoMessage()    {}
func (*CSSendMsgReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d31604874e01146d, []int{5}
}

func (m *CSSendMsgReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CSSendMsgReq.Unmarshal(m, b)
}
func (m *CSSendMsgReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CSSendMsgReq.Marshal(b, m, deterministic)
}
func (m *CSSendMsgReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CSSendMsgReq.Merge(m, src)
}
func (m *CSSendMsgReq) XXX_Size() int {
	return xxx_messageInfo_CSSendMsgReq.Size(m)
}
func (m *CSSendMsgReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CSSendMsgReq.DiscardUnknown(m)
}

var xxx_messageInfo_CSSendMsgReq proto.InternalMessageInfo

func (m *CSSendMsgReq) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

type SCSendMsgAck struct {
	Msg                  []byte   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SCSendMsgAck) Reset()         { *m = SCSendMsgAck{} }
func (m *SCSendMsgAck) String() string { return proto.CompactTextString(m) }
func (*SCSendMsgAck) ProtoMessage()    {}
func (*SCSendMsgAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_d31604874e01146d, []int{6}
}

func (m *SCSendMsgAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SCSendMsgAck.Unmarshal(m, b)
}
func (m *SCSendMsgAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SCSendMsgAck.Marshal(b, m, deterministic)
}
func (m *SCSendMsgAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SCSendMsgAck.Merge(m, src)
}
func (m *SCSendMsgAck) XXX_Size() int {
	return xxx_messageInfo_SCSendMsgAck.Size(m)
}
func (m *SCSendMsgAck) XXX_DiscardUnknown() {
	xxx_messageInfo_SCSendMsgAck.DiscardUnknown(m)
}

var xxx_messageInfo_SCSendMsgAck proto.InternalMessageInfo

func (m *SCSendMsgAck) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

func init() {
	proto.RegisterType((*ServiceIdentifyACK)(nil), "pbgo.ServiceIdentifyACK")
	proto.RegisterType((*PingReq)(nil), "pbgo.PingReq")
	proto.RegisterType((*PingAck)(nil), "pbgo.PingAck")
	proto.RegisterType((*CSPingReq)(nil), "pbgo.CSPingReq")
	proto.RegisterType((*SCPingAck)(nil), "pbgo.SCPingAck")
	proto.RegisterType((*CSSendMsgReq)(nil), "pbgo.CSSendMsgReq")
	proto.RegisterType((*SCSendMsgAck)(nil), "pbgo.SCSendMsgAck")
}

func init() { proto.RegisterFile("framework.proto", fileDescriptor_d31604874e01146d) }

var fileDescriptor_d31604874e01146d = []byte{
	// 216 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0x89, 0xbb, 0x28, 0x99, 0x16, 0x56, 0x73, 0xea, 0x45, 0xa8, 0x3d, 0x2d, 0x1e, 0xbc,
	0xf8, 0x04, 0x25, 0x27, 0x11, 0x45, 0x12, 0xef, 0x25, 0xdb, 0xce, 0x96, 0x50, 0x92, 0xd4, 0x24,
	0x28, 0x5e, 0x7d, 0x72, 0x49, 0xdb, 0x9c, 0xf6, 0xf6, 0xcf, 0xf7, 0x7f, 0x0c, 0xc3, 0xc0, 0xe1,
	0xec, 0x95, 0xc1, 0x1f, 0xe7, 0xa7, 0xa7, 0xd9, 0xbb, 0xe8, 0xd8, 0x7e, 0x3e, 0x8d, 0xae, 0xf9,
	0x23, 0xc0, 0x24, 0xfa, 0x6f, 0xdd, 0xe3, 0xcb, 0x80, 0x36, 0xea, 0xf3, 0x6f, 0xcb, 0x5f, 0xd9,
	0x03, 0x94, 0x61, 0xa5, 0x9d, 0x55, 0x06, 0x2b, 0x52, 0x93, 0x23, 0x15, 0xc5, 0xc6, 0xde, 0x95,
	0x41, 0x76, 0x0f, 0x90, 0x15, 0x3d, 0x54, 0x57, 0x8b, 0x40, 0x43, 0x5e, 0xc5, 0x1e, 0xe1, 0x2e,
	0x0d, 0xe8, 0xbb, 0x10, 0x95, 0x8f, 0x5d, 0xd4, 0x06, 0xab, 0x5d, 0x4d, 0x8e, 0x7b, 0x71, 0x58,
	0x0b, 0x99, 0xf8, 0xa7, 0x36, 0xd8, 0x50, 0xb8, 0xf9, 0xd0, 0x76, 0x14, 0xf8, 0x95, 0x63, 0xdb,
	0x4f, 0x4d, 0x01, 0x94, 0xcb, 0xcc, 0x0b, 0xa0, 0x92, 0xe7, 0xa6, 0x86, 0x92, 0x4b, 0x89, 0x76,
	0x78, 0x0b, 0xa9, 0x64, 0xb7, 0xb0, 0x33, 0x61, 0x5c, 0x8e, 0x2c, 0x45, 0x8a, 0xc9, 0x90, 0x7c,
	0x33, 0xda, 0x7e, 0xba, 0x34, 0x4e, 0xd7, 0xcb, 0x17, 0x9e, 0xff, 0x03, 0x00, 0x00, 0xff, 0xff,
	0x8a, 0x13, 0x6e, 0x16, 0x18, 0x01, 0x00, 0x00,
}
