// Code generated by protoc-gen-go. DO NOT EDIT.
// source: login.proto

package pbgo

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 登录操作
type CSLoginReq struct {
	Platform             string   `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	PhonePlatform        int32    `protobuf:"varint,2,opt,name=phone_platform,json=phonePlatform,proto3" json:"phone_platform,omitempty"`
	PlatformToken        string   `protobuf:"bytes,3,opt,name=platform_token,json=platformToken,proto3" json:"platform_token,omitempty"`
	OpenId               string   `protobuf:"bytes,4,opt,name=open_id,json=openId,proto3" json:"open_id,omitempty"`
	GameVersion          int32    `protobuf:"varint,7,opt,name=game_version,json=gameVersion,proto3" json:"game_version,omitempty"`
	Ip                   string   `protobuf:"bytes,8,opt,name=ip,proto3" json:"ip,omitempty"`
	SelectZone           int32    `protobuf:"varint,9,opt,name=select_zone,json=selectZone,proto3" json:"select_zone,omitempty"`
	SubPlatform          string   `protobuf:"bytes,10,opt,name=sub_platform,json=subPlatform,proto3" json:"sub_platform,omitempty"`
	UserId               string   `protobuf:"bytes,11,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CSLoginReq) Reset()         { *m = CSLoginReq{} }
func (m *CSLoginReq) String() string { return proto.CompactTextString(m) }
func (*CSLoginReq) ProtoMessage()    {}
func (*CSLoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{0}
}

func (m *CSLoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CSLoginReq.Unmarshal(m, b)
}
func (m *CSLoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CSLoginReq.Marshal(b, m, deterministic)
}
func (m *CSLoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CSLoginReq.Merge(m, src)
}
func (m *CSLoginReq) XXX_Size() int {
	return xxx_messageInfo_CSLoginReq.Size(m)
}
func (m *CSLoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CSLoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_CSLoginReq proto.InternalMessageInfo

func (m *CSLoginReq) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *CSLoginReq) GetPhonePlatform() int32 {
	if m != nil {
		return m.PhonePlatform
	}
	return 0
}

func (m *CSLoginReq) GetPlatformToken() string {
	if m != nil {
		return m.PlatformToken
	}
	return ""
}

func (m *CSLoginReq) GetOpenId() string {
	if m != nil {
		return m.OpenId
	}
	return ""
}

func (m *CSLoginReq) GetGameVersion() int32 {
	if m != nil {
		return m.GameVersion
	}
	return 0
}

func (m *CSLoginReq) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *CSLoginReq) GetSelectZone() int32 {
	if m != nil {
		return m.SelectZone
	}
	return 0
}

func (m *CSLoginReq) GetSubPlatform() string {
	if m != nil {
		return m.SubPlatform
	}
	return ""
}

func (m *CSLoginReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type SCLoginAck struct {
	Error                int32    `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	ClientId             uint64   `protobuf:"varint,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SCLoginAck) Reset()         { *m = SCLoginAck{} }
func (m *SCLoginAck) String() string { return proto.CompactTextString(m) }
func (*SCLoginAck) ProtoMessage()    {}
func (*SCLoginAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{1}
}

func (m *SCLoginAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SCLoginAck.Unmarshal(m, b)
}
func (m *SCLoginAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SCLoginAck.Marshal(b, m, deterministic)
}
func (m *SCLoginAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SCLoginAck.Merge(m, src)
}
func (m *SCLoginAck) XXX_Size() int {
	return xxx_messageInfo_SCLoginAck.Size(m)
}
func (m *SCLoginAck) XXX_DiscardUnknown() {
	xxx_messageInfo_SCLoginAck.DiscardUnknown(m)
}

var xxx_messageInfo_SCLoginAck proto.InternalMessageInfo

func (m *SCLoginAck) GetError() int32 {
	if m != nil {
		return m.Error
	}
	return 0
}

func (m *SCLoginAck) GetClientId() uint64 {
	if m != nil {
		return m.ClientId
	}
	return 0
}

func init() {
	proto.RegisterType((*CSLoginReq)(nil), "pbgo.CSLoginReq")
	proto.RegisterType((*SCLoginAck)(nil), "pbgo.SCLoginAck")
}

func init() { proto.RegisterFile("login.proto", fileDescriptor_67c21677aa7f4e4f) }

var fileDescriptor_67c21677aa7f4e4f = []byte{
	// 274 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x41, 0x4f, 0x83, 0x40,
	0x10, 0x85, 0x03, 0x42, 0x81, 0xc1, 0xf6, 0xb0, 0x31, 0xe9, 0x46, 0x0f, 0xd6, 0x26, 0x26, 0x3d,
	0x79, 0xf1, 0x07, 0x18, 0xd3, 0x13, 0x89, 0x07, 0x43, 0x8d, 0x07, 0x2f, 0xa4, 0xc0, 0x88, 0x9b,
	0xd2, 0x9d, 0x75, 0x01, 0x0f, 0xfe, 0x19, 0xff, 0xaa, 0xd9, 0x41, 0xd1, 0xdb, 0xbe, 0x6f, 0xe7,
	0xcd, 0xbc, 0x3c, 0x48, 0x5b, 0x6a, 0x94, 0xbe, 0x31, 0x96, 0x7a, 0x12, 0x81, 0x29, 0x1b, 0x5a,
	0x7f, 0xf9, 0x00, 0xdb, 0xdd, 0x83, 0xe3, 0x39, 0xbe, 0x8b, 0x73, 0x88, 0x4d, 0xbb, 0xef, 0x5f,
	0xc9, 0x1e, 0xa5, 0xb7, 0xf2, 0x36, 0x49, 0x3e, 0x69, 0x71, 0x0d, 0x0b, 0xf3, 0x46, 0x1a, 0x8b,
	0x69, 0xc2, 0x5f, 0x79, 0x9b, 0x30, 0x9f, 0x33, 0x7d, 0xfc, 0x3f, 0xf6, 0xf3, 0x2e, 0x7a, 0x3a,
	0xa0, 0x96, 0x27, 0xbc, 0x68, 0xfe, 0x4b, 0x9f, 0x1c, 0x14, 0x4b, 0x88, 0xc8, 0xa0, 0x2e, 0x54,
	0x2d, 0x03, 0xfe, 0x9f, 0x39, 0x99, 0xd5, 0xe2, 0x0a, 0x4e, 0x9b, 0xfd, 0x11, 0x8b, 0x0f, 0xb4,
	0x9d, 0x22, 0x2d, 0x23, 0x3e, 0x92, 0x3a, 0xf6, 0x3c, 0x22, 0xb1, 0x00, 0x5f, 0x19, 0x19, 0xb3,
	0xcd, 0x57, 0x46, 0x5c, 0x42, 0xda, 0x61, 0x8b, 0x55, 0x5f, 0x7c, 0x92, 0x46, 0x99, 0xb0, 0x03,
	0x46, 0xf4, 0x42, 0x1a, 0xdd, 0xce, 0x6e, 0x28, 0xff, 0x82, 0x03, 0x5b, 0xd3, 0x6e, 0x28, 0xa7,
	0xd8, 0x4b, 0x88, 0x86, 0x0e, 0xad, 0xcb, 0x93, 0x8e, 0x79, 0x9c, 0xcc, 0xea, 0xf5, 0x1d, 0xc0,
	0x6e, 0xcb, 0x05, 0xdd, 0x57, 0x07, 0x71, 0x06, 0x21, 0x5a, 0x4b, 0x96, 0xdb, 0x09, 0xf3, 0x51,
	0x88, 0x0b, 0x48, 0xaa, 0x56, 0xa1, 0xee, 0x9d, 0xdd, 0xb5, 0x12, 0xe4, 0xf1, 0x08, 0xb2, 0xba,
	0x9c, 0x71, 0xdf, 0xb7, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc2, 0xab, 0x3c, 0x3b, 0x7e, 0x01,
	0x00, 0x00,
}
