// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: messagedef.proto

package pbgo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProtoMsgId int32

const (
	ProtoMsgId_MSG_BEGIN             ProtoMsgId = 0
	ProtoMsgId_SERVICE_IDENTIFY_ACK  ProtoMsgId = 1    //	ServiceIdentifyACK **ServiceIdentifyACK **framework.proto ** [ServiceIdentifyACK]
	ProtoMsgId_PING_REQ              ProtoMsgId = 2    //	PingReq **PingReq **framework.proto ** [PingReq]
	ProtoMsgId_PING_ACK              ProtoMsgId = 3    //	PingAck **PingAck **framework.proto ** [PingAck]
	ProtoMsgId_CS_PING_REQ           ProtoMsgId = 4    //	CSPingReq **CSPingReq **framework.proto ** [CSPingReq]
	ProtoMsgId_SC_PING_ACK           ProtoMsgId = 5    //	SCPingAck **SCPingAck **framework.proto ** [SCPingAck]
	ProtoMsgId_CS_SEND_MSG_REQ       ProtoMsgId = 6    //	CSSendMsgReq **CSSendMsgReq **framework.proto ** [CSSendMsgReq]
	ProtoMsgId_SC_SEND_MSG_ACK       ProtoMsgId = 7    //	SCSendMsgAck **SCSendMsgAck **framework.proto ** [SCSendMsgAck]
	ProtoMsgId_MSG_TRANSMIT_NTF      ProtoMsgId = 8    //	MsgTransmitNtf **MsgTransmitNtf **framework.proto ** [MsgTransmitNtf]
	ProtoMsgId_WS_SESSION_CLOSED_NTF ProtoMsgId = 9    //	WSSessionClosedNtf **WSSessionClosedNtf **framework.proto ** [WSSessionClosedNtf]
	ProtoMsgId_CS_LOGIN_REQ          ProtoMsgId = 1000 //	CSLoginReq **CSLoginReq **login.proto ** [CSLoginReq]
	ProtoMsgId_SC_LOGIN_ACK          ProtoMsgId = 1001 //	SCLoginAck **SCLoginAck **login.proto ** [SCLoginAck]
	ProtoMsgId_CS_CREATE_ROLE_REQ    ProtoMsgId = 5000 //	CSCreateRoleReq **CSCreateRoleReq **user.proto ** [CSCreateRoleReq]
	ProtoMsgId_SC_CREATE_ROLE_ACK    ProtoMsgId = 5001 //	SCCreateRoleAck **SCCreateRoleAck **user.proto ** [SCCreateRoleAck]
)

// Enum value maps for ProtoMsgId.
var (
	ProtoMsgId_name = map[int32]string{
		0:    "MSG_BEGIN",
		1:    "SERVICE_IDENTIFY_ACK",
		2:    "PING_REQ",
		3:    "PING_ACK",
		4:    "CS_PING_REQ",
		5:    "SC_PING_ACK",
		6:    "CS_SEND_MSG_REQ",
		7:    "SC_SEND_MSG_ACK",
		8:    "MSG_TRANSMIT_NTF",
		9:    "WS_SESSION_CLOSED_NTF",
		1000: "CS_LOGIN_REQ",
		1001: "SC_LOGIN_ACK",
		5000: "CS_CREATE_ROLE_REQ",
		5001: "SC_CREATE_ROLE_ACK",
	}
	ProtoMsgId_value = map[string]int32{
		"MSG_BEGIN":             0,
		"SERVICE_IDENTIFY_ACK":  1,
		"PING_REQ":              2,
		"PING_ACK":              3,
		"CS_PING_REQ":           4,
		"SC_PING_ACK":           5,
		"CS_SEND_MSG_REQ":       6,
		"SC_SEND_MSG_ACK":       7,
		"MSG_TRANSMIT_NTF":      8,
		"WS_SESSION_CLOSED_NTF": 9,
		"CS_LOGIN_REQ":          1000,
		"SC_LOGIN_ACK":          1001,
		"CS_CREATE_ROLE_REQ":    5000,
		"SC_CREATE_ROLE_ACK":    5001,
	}
)

func (x ProtoMsgId) Enum() *ProtoMsgId {
	p := new(ProtoMsgId)
	*p = x
	return p
}

func (x ProtoMsgId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProtoMsgId) Descriptor() protoreflect.EnumDescriptor {
	return file_messagedef_proto_enumTypes[0].Descriptor()
}

func (ProtoMsgId) Type() protoreflect.EnumType {
	return &file_messagedef_proto_enumTypes[0]
}

func (x ProtoMsgId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProtoMsgId.Descriptor instead.
func (ProtoMsgId) EnumDescriptor() ([]byte, []int) {
	return file_messagedef_proto_rawDescGZIP(), []int{0}
}

var File_messagedef_proto protoreflect.FileDescriptor

const file_messagedef_proto_rawDesc = "" +
	"\n" +
	"\x10messagedef.proto\x12\x04pbgo*\xa6\x02\n" +
	"\n" +
	"protoMsgId\x12\r\n" +
	"\tMSG_BEGIN\x10\x00\x12\x18\n" +
	"\x14SERVICE_IDENTIFY_ACK\x10\x01\x12\f\n" +
	"\bPING_REQ\x10\x02\x12\f\n" +
	"\bPING_ACK\x10\x03\x12\x0f\n" +
	"\vCS_PING_REQ\x10\x04\x12\x0f\n" +
	"\vSC_PING_ACK\x10\x05\x12\x13\n" +
	"\x0fCS_SEND_MSG_REQ\x10\x06\x12\x13\n" +
	"\x0fSC_SEND_MSG_ACK\x10\a\x12\x14\n" +
	"\x10MSG_TRANSMIT_NTF\x10\b\x12\x19\n" +
	"\x15WS_SESSION_CLOSED_NTF\x10\t\x12\x11\n" +
	"\fCS_LOGIN_REQ\x10\xe8\a\x12\x11\n" +
	"\fSC_LOGIN_ACK\x10\xe9\a\x12\x17\n" +
	"\x12CS_CREATE_ROLE_REQ\x10\x88'\x12\x17\n" +
	"\x12SC_CREATE_ROLE_ACK\x10\x89'B\bZ\x06.;pbgob\x06proto3"

var (
	file_messagedef_proto_rawDescOnce sync.Once
	file_messagedef_proto_rawDescData []byte
)

func file_messagedef_proto_rawDescGZIP() []byte {
	file_messagedef_proto_rawDescOnce.Do(func() {
		file_messagedef_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_messagedef_proto_rawDesc), len(file_messagedef_proto_rawDesc)))
	})
	return file_messagedef_proto_rawDescData
}

var file_messagedef_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_messagedef_proto_goTypes = []any{
	(ProtoMsgId)(0), // 0: pbgo.protoMsgId
}
var file_messagedef_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_messagedef_proto_init() }
func file_messagedef_proto_init() {
	if File_messagedef_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_messagedef_proto_rawDesc), len(file_messagedef_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messagedef_proto_goTypes,
		DependencyIndexes: file_messagedef_proto_depIdxs,
		EnumInfos:         file_messagedef_proto_enumTypes,
	}.Build()
	File_messagedef_proto = out.File
	file_messagedef_proto_goTypes = nil
	file_messagedef_proto_depIdxs = nil
}
