// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package pbgo

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AccountRole struct {
	OpenId               string   `protobuf:"bytes,1,opt,name=open_id,json=openId,proto3" json:"open_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountRole) Reset()         { *m = AccountRole{} }
func (m *AccountRole) String() string { return proto.CompactTextString(m) }
func (*AccountRole) ProtoMessage()    {}
func (*AccountRole) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *AccountRole) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountRole.Unmarshal(m, b)
}
func (m *AccountRole) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountRole.Marshal(b, m, deterministic)
}
func (m *AccountRole) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountRole.Merge(m, src)
}
func (m *AccountRole) XXX_Size() int {
	return xxx_messageInfo_AccountRole.Size(m)
}
func (m *AccountRole) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountRole.DiscardUnknown(m)
}

var xxx_messageInfo_AccountRole proto.InternalMessageInfo

func (m *AccountRole) GetOpenId() string {
	if m != nil {
		return m.OpenId
	}
	return ""
}

func init() {
	proto.RegisterType((*AccountRole)(nil), "pbgo.AccountRole")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 85 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x2d, 0x4e, 0x2d,
	0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x29, 0x48, 0x4a, 0xcf, 0x57, 0x52, 0xe3, 0xe2,
	0x76, 0x4c, 0x4e, 0xce, 0x2f, 0xcd, 0x2b, 0x09, 0xca, 0xcf, 0x49, 0x15, 0x12, 0xe7, 0x62, 0xcf,
	0x2f, 0x48, 0xcd, 0x8b, 0xcf, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x62, 0x03, 0x71,
	0x3d, 0x53, 0x92, 0xd8, 0xc0, 0x9a, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x7d, 0xc6, 0xa6,
	0xce, 0x42, 0x00, 0x00, 0x00,
}
